### ISSUE TITLE
Codebook for the variables

### ISSUE THREAD

**Issue by mdragt** [microsoft/ignite-learning-paths#40]
Hi! Would it be possible to get a codebook for the variables, explaining the meaning of them?

**Comment by amynic** [comment]
Hi @mdragt is this located within a specific session? could you provide an example?

**Comment by mdragt** [comment]
Sure: i.e. for this dataset https://github.com/microsoft/ignite-learning-paths/blob/master/aiml/aiml30/README.md

**Comment by FBoucher** [comment]
I close this issur since the content as been moved to [https://github.com/microsoft/ignite-learning-paths-training-aiml](https://github.com/microsoft/ignite-learning-paths-training-aiml).

If you still need clarification please re-create the issue over there.
Thank you.
