### ISSUE TITLE
Apps40 steps not very clear

### ISSUE THREAD

**Issue by cheahengsoon** [microsoft/ignite-learning-paths#89]
A few questions in Apps 40:
1. The service principal Id and Password is get from az ad sp create-for-rbac ?ServicePrincipalID Refer to appid or name ?
2. After done the deployment , the container status always fail.
3. I can't find the Connection Information like shown in screenshot , is that we need to wait until finish deployment?
4.  How we can navigate to Running scale demo,Network policy and Availability zones, the step not clear?

**Updated on 27 November 2019.**

**Comment by FBoucher** [comment]
Hello @cheahengsoon Thank you for your feedback. 
May I ask you to re-create it in the APPS repository (https://github.com/microsoft/ignite-learning-paths-training-apps)

This current one is not used anymore. Thanks
