### ISSUE TITLE
Clarifications in Tailwind OPS LP Deployment

### ISSUE THREAD

**Issue by alspeirs** [microsoft/ignite-learning-paths#90]
A couple of suggested notes to add in readme.md:

- Certain steps require specific services that can't be deployed in an MSDN subscription, or are unavailable in certain regions. Would be good to call out the components used and to recommend an appropriate region

- Before provisioning, use **az account set --subscription <name or id>** to target deployment steps to correct subscription

**Comment by FBoucher** [comment]
Hello @alspeirs,
Thank you for your feedback. Unfortunately, the content as been moved to nother repo ([https://github.com/microsoft/ignite-learning-paths-training-ops](https://github.com/microsoft/ignite-learning-paths-training-ops))

I will invite you to re-create the issue over there. I will close this one.

Regards
